name: PHP Syntax Check (Unit Test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  php-syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP syntax check
        run: |
          find src -name "*.php" -print0 | xargs -0 -n1 php -l
